name: ArcticTools
authors: [ KyroKrypt, Finn ]
version: 1.0.0
main: dev.arcticdevelopment.arctictools.ArcticTools
description: Template plugin
softdepend: [ WorldGuard ]
commands:
  rod:
  fishtop:
  crystals: